### ISSUE TITLE
cloudflare

### ISSUE THREAD

**Issue by veeramarni** [MySocialApp/kubernetes-helm-chart-traefik#1]
What is the reason you have cloudflare in the `daemonset` file? Just curious to find out.

**Comment by deimosfr** [comment]
Hi,

As described in the readme, it is used to:

* Manage let's encrypt certificates with DNS challenge on Cloudflare
* Manage Cloudflare DNS to register and unregister on start and stop (useful if you do not have a load balancer on top of Traefik

Is this enough clear? Please let me know if it's not. 

Thanks

**Comment by veeramarni** [comment]
I just want to understand the second point. If we deploy it in gke which comes with its standard loadbalancer, the External IP generated will be automatically registered in the cloudflare? Since the public IP changes each install of helm right?

Appreciate your clarification.

**Comment by deimosfr** [comment]
Oh well ok I got it. Let me explain to you how it work on my side:

When you're running on premise environment, one thing is to make round robin on you physical hosts. My ingress services are redirected to this round robin name. That mean if I reboot a node, I'm going to get 1 miss on X nodes.

To avoid that, when a traefik is going to be shutdown, I'm automatically removing this node from the round robin DNS name. This way, I ensure I won't get miss. Then, when it start again, I'm re-adding in in the round robin pool and checking its presence against several public DNS servers.

I'm going to add more details in the readme.

Is this more clear ?
